name: "Release"

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: '--bundles nsis'
            sidecar_target: 'node18-win-x64'
            sidecar_name: 'sidecar-x86_64-pc-windows-msvc.exe'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: pnpm install

      - name: Compile Sidecar with NCC and pkg
        run: |
          cd sidecar
          pnpm install
          npx @vercel/ncc build index.js -o dist
          npx pkg dist/index.js -t ${{ matrix.sidecar_target }} -o ../src-tauri/${{ matrix.sidecar_name }}

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "WhatsRemind ${{ github.ref_name }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
